# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: nice_nano_v2
    shield: sofle_dt_left
  - board: nice_nano_v2
    shield: sofle_dt_right

  # Alternative PINs firmware
  # This builds an additional firmware for the left half that overrides the
  # pins configured in `sofle_dt_left.overlay` and creates a firmware that
  # uses the high frequency pins D1 for SCL and D2 for SDA.
  #
  # You can remove this entry in your own zmk-config.
  - board: nice_nano_v2
    shield: sofle_dt_left
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DMOUSE_PS2_ALT_PINS
    artifact-name: sofle_dt_left-nice_nano_v2-scl_D1_sda_D0-zmk